let mongoose = require('mongoose');
let timeZone = require('mongoose-timezone');
let UserSchema = new mongoose.Schema({
  ac_year:String,
  amount:String,
  building_type:String,
  bundle_discount:String,
  central_bulgar_alarm:String,
  central_fire_alarm:String,
  construction_type:String,
  county:String,
  deadbolt_locks:String,
  electric_year:String,
  estimate:String,
  exterior_type:String,
  foundation_type:String,
  hippoPrice:String,
  isGooglePlace:String,
  is_basement:String,
  plumbing_year:String,
  roof_status:String,
  roof_type:String,
  roof_year:String,
  zip_code:String,
  start_date: {
    type: Date,
    default:Date.now()
  },
  email: String,
  quote_id: String,
  address: {type:String,default:''},
  city: {type:String,default:''},
  state: {type:String,default:''},
  alarm: Boolean,
  bundle: Boolean,
  delivery: Boolean,
  low_price: String,
  high_price: String,
  year_built:String,
  sqft:String,
  bind_now: {type: Boolean, default: false},
  bind_now_price: String,
  hand_off: {type:Boolean, default:false},
  hand_off_from: {type:String, default:''},
  hand_off_from_email: {type:String, default:''},
  hand_off_to: {type:String, default:''},
  cars: {type:Array, default:''},
  policy_start_date:String,
  policy:Boolean,
  policy_number:String,
  personData:Array,
  insurance_data:String,
  mortgage:Boolean,
  mortgage_name:String,
  continue_name:String,
  mortgage_street:String,
  mortgage_city:String,
  mortgage_state:String,
  mortgage_postal_code:String,
  mortgage_company:String,
  lender_email:String,
  loan:String,
  mortgage_start_date: {
    type: String
  },
  mortgage_effective_date: {
    type: String
  },
  mortgage_expiration_date: {
    type: String
  },
  policy_document_url:String,
  insuranceType:String,
  mode:Number,
  phone:String,
  created_at: {type: Date, default: Date.now()},
});
module.exports = mongoose.model('User', UserSchema);
UserSchema.plugin(timeZone, {paths: ['start_date', 'end_date']});
